# Generated by Django 5.2.5 on 2025-08-20 23:43

import apps.events.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_title', models.CharField(max_length=255, verbose_name='عنوان محل برگزاری')),
                ('address', models.TextField(verbose_name='آدرس محل برگزاری')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.events.models.upload_image_venue, verbose_name=' تصویر رویداد')),
            ],
            options={
                'verbose_name': 'محل برگزاری',
                'verbose_name_plural': 'محل های محل برگزاری ها',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('ongoing', 'ongoing'), ('held', 'held'), ('cancelled', 'Cancelled'), ('soldout', 'soldout')], max_length=20)),
                ('seats_total', models.PositiveIntegerField()),
                ('seats_left', models.PositiveIntegerField()),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد ')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مبلغ')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.events.models.upload_image_event, verbose_name=' تصویر رویداد')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='سازنده رویداد')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.venue', verbose_name=' محل برگزاری')),
            ],
            options={
                'verbose_name': 'رویداد',
                'verbose_name_plural': 'رویداد ها',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_count', models.PositiveIntegerField(default=1, verbose_name='تعداد بلیط')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event', verbose_name='رویداد')),
            ],
            options={
                'verbose_name': 'رزرو ',
                'verbose_name_plural': 'رزرو ها',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='شماره پیگیری')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('success', 'موفق'), ('failed', 'ناموفق')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='events.booking')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت ها',
            },
        ),
    ]
