# Generated by Django 5.2.5 on 2025-08-28 16:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('ongoing', 'ongoing'), ('held', 'held'), ('cancelled', 'Cancelled'), ('soldout', 'soldout')], default='ongoing', max_length=20),
        ),
    ]
